// frontend/angular/src/app/components/login/login.component.ts
import { Component } from '@angular/core';
import {AuthenticationRequest} from "../../models/authentication-request";
import {AuthenticationService} from "../../services/authentication/authentication.service";
import { Router } from '@angular/router';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss']
})
export class LoginComponent {

  authenticationRequest: AuthenticationRequest = {};

  errorMsg = '';

  constructor(
    private authenticationService: AuthenticationService,
    private router: Router
  ) {
  }

  login() {
    this.errorMsg = '';
    this.authenticationService.login(this.authenticationRequest)
      .subscribe({
        next: (authenticationResponse) => {
          localStorage.setItem('user', JSON.stringify(authenticationResponse));
          this.router.navigate(['customers']);
    },
        error: (err) => {
          if (err.error.statusCode === 401) {
            this.errorMsg = 'Login and / or password is incorrect';
          }
        }
      });
  }

  register() {
    this.router.navigate(['register']);
  }
}

<div class="flex" style="height: 100vh">
  <div class="col-6 m-3 flex flex-column justify-content-center">
    <div class="m-auto">
      <div class="text-center">
        <p-avatar
          image="https://fikiwiki.com/uploads/posts/2022-02/1645039704_16-fikiwiki-com-p-kartinki-logotipov-16.png"
          styleClass="mr-2"
          size="xlarge"
          shape="circle"
        ></p-avatar>
        <h1>Sign in to your account</h1>
      </div>
      <p-message
        *ngIf="errorMsg"
        severity="error"
        [text]="errorMsg"
        styleClass="mb-2 w-full"
      ></p-message>
      <div class="field">
        <label for="email">Email</label>
        <input
          [(ngModel)]="authenticationRequest.username"
          id="email"
          pInputText
          placeholder="Jane@raisbex.ru"
          type="email"
          class="w-full"
        >
      </div>
      <div class="field">
        <label for="password">Password</label>
        <input
          [(ngModel)]="authenticationRequest.password"
          id="password"
          pInputText
          placeholder="Password"
          type="password"
          class="w-full"
        >
      </div>
      <button
        pButton
        label="Login"
        class="w-full"
        (click)="login()"
      ></button>
      <button
        pButton
        label="Don't have an account? Signup now."
        class="w-full p-button-link text-left pl-0"
        (click)="register()"
      ></button>
    </div>
  </div>
  <div class="col-6 flex flex-column justify-content-center align-items-center right-container">
    <h1>
      <a href="https://amigoscode.com/courses" target="_blank">Enrol Now</a>
    </h1>
    <img
      class="background p-6 pt-0"
      src="https://user-images.githubusercontent.com/40702606/215539167-d7006790-b880-4929-83fb-c43fa74f429e.png"
    >
  </div>
</div>

// frontend/react/src/components/login/Login.jsx
import {
    Alert,
    AlertIcon,
    Box,
    Button,
    Flex,
    FormLabel,
    Heading,
    Image,
    Input,
    Link,
    Stack,
    Text,
} from '@chakra-ui/react';
import {Formik, Form, useField} from "formik";
import * as Yup from 'yup';
import {useAuth} from "../context/AuthContext.jsx";
import {errorNotification} from "../../services/notification.js";
import {useNavigate} from "react-router-dom";
import {useEffect} from "react";

const MyTextInput = ({label, ...props}) => {
    // useField() returns [formik.getFieldProps(), formik.getFieldMeta()]
    // which we can spread on <input>. We can use field meta to show an error
    // message if the field is invalid and it has been touched (i.e. visited)
    const [field, meta] = useField(props);
    return (
        <Box>
            <FormLabel htmlFor={props.id || props.name}>{label}</FormLabel>
            <Input className="text-input" {...field} {...props} />
            {meta.touched && meta.error ? (
                <Alert className="error" status={"error"} mt={2}>
                    <AlertIcon/>
                    {meta.error}
                </Alert>
            ) : null}
        </Box>
    );
};

const LoginForm = () => {
    const { login } = useAuth();
    const navigate = useNavigate();

    return (
        <Formik
            validateOnMount={true}
            validationSchema={
                Yup.object({
                    username: Yup.string()
                        .email("Must be valid email")
                        .required("Email is required"),
                    password: Yup.string()
                        .max(20, "Password cannot be more than 20 characters")
                        .required("Password is required")
                })
            }
            initialValues={{username: '', password: ''}}
            onSubmit={(values, {setSubmitting}) => {
                setSubmitting(true);
                login(values).then(res => {
                    navigate("/dashboard")
                    console.log("Successfully logged in");
                }).catch(err => {
                    errorNotification(
                        err.code,
                        err.response.data.message
                    )
                }).finally(() => {
                    setSubmitting(false);
                })
            }}>

            {({isValid, isSubmitting}) => (
                <Form>
                    <Stack mt={15} spacing={15}>
                        <MyTextInput
                            label={"Email"}
                            name={"username"}
                            type={"email"}
                            placeholder={"hello@raisbex.ru"}
                        />
                        <MyTextInput
                            label={"Password"}
                            name={"password"}
                            type={"password"}
                            placeholder={"Type your password"}
                        />

                        <Button
                            type={"submit"}
                            disabled={!isValid || isSubmitting}>
                            Login
                        </Button>
                    </Stack>
                </Form>
            )}

        </Formik>
    )
}

const Login = () => {

    const { customer } = useAuth();
    const navigate = useNavigate();

    useEffect(() => {
        if (customer) {
            navigate("/dashboard/customers");
        }
    })

    return (
        <Stack minH={'100vh'} direction={{base: 'column', md: 'row'}}>
            <Flex p={8} flex={1} alignItems={'center'} justifyContent={'center'}>
                <Stack spacing={4} w={'full'} maxW={'md'}>
                    <Image
                        src={"https://fikiwiki.com/uploads/posts/2022-02/1645039704_16-fikiwiki-com-p-kartinki-logotipov-16.png"}
                        boxSize={"200px"}
                        alt={"Raisbex Logo"}
                        alignSelf={"center"}
                    />
                    <Heading fontSize={'2xl'} mb={15}>Sign in to your account</Heading>
                    <LoginForm/>
                    <Link color={"blue.500"} href={"/signup"}>
                        Dont have an account? Signup now.
                    </Link>
                </Stack>
            </Flex>
            <Flex
                flex={1}
                p={10}
                flexDirection={"column"}
                alignItems={"center"}
                justifyContent={"center"}
                bgGradient={{sm: 'linear(to-r, blue.600, purple.600)'}}
            >
                <Text fontSize={"6xl"} color={'white'} fontWeight={"bold"} mb={5}>
                    <Link target={"_blank"} href={"https://amigoscode.com/courses"}>
                        Enrol Now
                    </Link>
                </Text>
                <Image
                    alt={'Login Image'}
                    objectFit={'scale-down'}
                    src={
                        'https://user-images.githubusercontent.com/40702606/215539167-d7006790-b880-4929-83fb-c43fa74f429e.png'
                    }
                />
            </Flex>
        </Stack>
    );
}

export default Login;
